name: CI

on:
  push:
    branches:
      - main
  pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

# Cancel existing tests on the same PR if a new commit is added to a pull request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    runs-on: ${{ matrix.runner.os }}
    # The test suite is super short and typically takes < 1 minute. If it takes
    # > 5 minutes it probably got hung on a failing test (e.g. an error that's
    # thrown inside the error hint itself)
    timeout-minutes: 5
    strategy:
      fail-fast: false

      matrix:
        runner:
          # Ubuntu
          - version: '1'
            os: ubuntu-latest
          # Windows
          - version: '1'
            os: windows-latest
          # macOS
          - version: '1'
            os: macos-latest
          # Minimum supported version (1.6)
          - version: 'min'
            os: ubuntu-latest
          # lts (1.10)
          - version: 'lts'
            os: ubuntu-latest
          # 1.11 (for good measure)
          - version: '1.11'
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.runner.version }}

      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1
